[package]
name = "sdtm-model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "SDTM data model definitions"

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
