[package]
name = "tss-validate"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "CDISC conformance validation for SDTM, ADaM, and SEND"

[lints]
workspace = true

[dependencies]
polars.workspace = true
regex = "1.12.2"
tss-model = { path = "../tss-model" }
serde = { workspace = true, features = ["derive"] }
