[workspace]
members = [
    "crates/sdtm-cli",
    "crates/sdtm-core",
    "crates/sdtm-ingest",
    "crates/sdtm-map",
    "crates/sdtm-model",
    "crates/sdtm-report",
    "crates/sdtm-standards",
    "crates/sdtm-validate",
    "crates/sdtm-xpt",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.92"

[workspace.dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
clap = { version = "4.5.53", features = ["derive"] }
csv = "1.4.0"
comfy-table = { version = "7.1.1", features = ["custom_styling"] }
hex = "0.4.3"
insta = { version = "1.45.0", features = ["json"] }
polars = { version = "0.52.0" }
quick-xml = "0.38.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.147"
sha2 = "0.10.9"
thiserror = "2.0.17"
tracing = "0.1.44"
indicatif = "0.18.3"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }

[profile.dev]
debug = 1
