[package]
name = "sdtm-validate"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
polars.workspace = true
serde.workspace = true
serde_json.workspace = true
sdtm-model = { path = "../sdtm-model" }
sdtm-standards = { path = "../sdtm-standards" }
