[predicates]
schema = "cdisc-transpiler.conformance-predicates"
schema_version = 1

[[predicate]]
name = "column_present"
kind = "table"
params = { column = "string", required_only = "bool" }

[[predicate]]
name = "non_missing"
kind = "row"
params = { column = "string" }

[[predicate]]
name = "unique_key"
kind = "table"
params = { columns = "string[]" }

[[predicate]]
name = "ct_membership"
kind = "row"
params = { column = "string", codelist = "string", extensible_ok = "bool" }
