[package]
name = "sdtm-map"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
sdtm-core = { path = "../sdtm-core" }
sdtm-model = { path = "../sdtm-model" }
