[package]
name = "sdtm-standards"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
csv.workspace = true
sdtm-model = { path = "../sdtm-model" }
serde = { workspace = true, features = ["derive"] }
thiserror = "2.0"
